import { supabase, isSupabaseConfigured } from '../lib/supabase';
import { notificationService } from './notificationService';

export const issueService = {
  /**
   * Fetch all campus issues with filtering, search, and ordering
   */
  async getIssues({ category, priority, status, search, sortBy = 'newest', limit = 50 } = {}) {
    if (!isSupabaseConfigured()) return [];

    let query = supabase
      .from('issues')
      .select(`
        *,
        reporter:profiles!reported_by(name, email),
        votes:issue_votes(count)
      `);

    // Apply Filters
    if (category && category !== 'All') {
      query = query.eq('category', category);
    }
    if (priority && priority !== 'All') {
      query = query.eq('priority', priority);
    }
    if (status && status !== 'All') {
      query = query.eq('status', status);
    }
    if (search && search.trim()) {
      const term = `%${search.trim()}%`;
      query = query.or(`title.ilike.${term},description.ilike.${term},issue_code.ilike.${term},location_name.ilike.${term}`);
    }

    // Apply Sorting
    if (sortBy === 'oldest') {
      query = query.order('created_at', { ascending: true });
    } else if (sortBy === 'priority') {
      // In PostgreSQL we can order by created_at desc as default secondary
      query = query.order('priority', { ascending: false }).order('created_at', { ascending: false });
    } else {
      query = query.order('created_at', { ascending: false });
    }

    if (limit) {
      query = query.limit(limit);
    }

    const { data, error } = await query;
    if (error) {
      console.error('Error fetching issues:', error);
      throw error;
    }

    // Map formatted vote counts
    const mapped = (data || []).map(issue => ({
      ...issue,
      voteCount: issue.votes?.[0]?.count || 0
    }));

    // In-memory sort for vote count if requested
    if (sortBy === 'votes') {
      mapped.sort((a, b) => (b.voteCount || 0) - (a.voteCount || 0));
    }

    return mapped;
  },

  /**
   * Get single issue details by ID with full audit history
   */
  async getIssueById(issueId) {
    if (!isSupabaseConfigured() || !issueId) return null;

    const { data: issue, error: issueError } = await supabase
      .from('issues')
      .select(`
        *,
        reporter:profiles!reported_by(name, email),
        votes:issue_votes(count)
      `)
      .eq('id', issueId)
      .single();

    if (issueError) {
      console.error('Error fetching issue details:', issueError);
      throw issueError;
    }

    // Fetch timeline updates
    const { data: updates, error: updateError } = await supabase
      .from('issue_updates')
      .select(`
        *,
        updater:profiles!updated_by(name, role)
      `)
      .eq('issue_id', issueId)
      .order('created_at', { ascending: true });

    if (updateError) {
      console.warn('Error fetching issue updates:', updateError);
    }

    return {
      ...issue,
      voteCount: issue.votes?.[0]?.count || 0,
      updates: updates || []
    };
  },

  /**
   * Fetch issues created by a specific student
   */
  async getMyIssues(userId) {
    if (!isSupabaseConfigured() || !userId) return [];

    const { data, error } = await supabase
      .from('issues')
      .select(`
        *,
        votes:issue_votes(count)
      `)
      .eq('reported_by', userId)
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching user issues:', error);
      throw error;
    }

    return (data || []).map(issue => ({
      ...issue,
      voteCount: issue.votes?.[0]?.count || 0
    }));
  },

  /**
   * Submit a new campus water & sanitation report
   */
  async createIssue({
    title,
    description,
    category,
    priority,
    photo_url = null,
    latitude = null,
    longitude = null,
    location_name,
    reported_by
  }) {
    if (!isSupabaseConfigured()) {
      throw new Error('Supabase is not configured.');
    }

    // 1. Insert issue record (issue_code is generated by DB trigger)
    const { data: issue, error } = await supabase
      .from('issues')
      .insert({
        title: title.trim(),
        description: description.trim(),
        category,
        priority: priority || 'Medium',
        status: 'Reported',
        photo_url,
        latitude: latitude ? parseFloat(latitude) : null,
        longitude: longitude ? parseFloat(longitude) : null,
        location_name,
        reported_by
      })
      .select()
      .single();

    if (error) {
      console.error('Error creating issue:', error);
      throw error;
    }

    // 2. Insert initial timeline entry in issue_updates
    try {
      await supabase
        .from('issue_updates')
        .insert({
          issue_id: issue.id,
          old_status: null,
          new_status: 'Reported',
          updated_by: reported_by,
          note: 'Issue reported by campus user.'
        });
    } catch (err) {
      console.warn('Could not write initial audit update:', err);
    }

    return issue;
  },

  /**
   * Admin workflow: Transition issue status, log update, send notification
   */
  async updateIssueStatus({
    issueId,
    newStatus,
    adminNote,
    resolutionPhotoUrl = null,
    adminId,
    currentIssue
  }) {
    if (!isSupabaseConfigured()) {
      throw new Error('Supabase is not configured.');
    }

    const oldStatus = currentIssue.status;
    const isResolved = newStatus === 'Resolved';

    // 1. Prepare updates object
    const updatePayload = {
      status: newStatus,
      admin_note: adminNote ? adminNote.trim() : currentIssue.admin_note,
      updated_at: new Date().toISOString()
    };

    if (resolutionPhotoUrl) {
      updatePayload.resolution_photo_url = resolutionPhotoUrl;
    }

    if (isResolved) {
      updatePayload.resolved_at = new Date().toISOString();
    }

    // 2. Update issue in database
    const { data: updatedIssue, error: updateError } = await supabase
      .from('issues')
      .update(updatePayload)
      .eq('id', issueId)
      .select()
      .single();

    if (updateError) {
      console.error('Error updating issue status:', updateError);
      throw updateError;
    }

    // 3. Create mandatory entry in issue_updates table
    const { error: logError } = await supabase
      .from('issue_updates')
      .insert({
        issue_id: issueId,
        old_status: oldStatus,
        new_status: newStatus,
        updated_by: adminId,
        note: adminNote || `Status updated from ${oldStatus} to ${newStatus}`
      });

    if (logError) {
      console.error('Error logging status transition:', logError);
    }

    // 4. Send in-app notification to the reporter
    if (currentIssue.reported_by) {
      let notifTitle = 'Status Update';
      let notifMessage = `Your report ${currentIssue.issue_code} status has changed to ${newStatus}.`;

      if (newStatus === 'In Progress') {
        notifTitle = 'Work in Progress';
        notifMessage = `Your report ${currentIssue.issue_code} is now being worked on.`;
      } else if (newStatus === 'Resolved') {
        notifTitle = 'Issue Resolved';
        notifMessage = `Your report ${currentIssue.issue_code} has been resolved.`;
      }

      await notificationService.createNotification(
        currentIssue.reported_by,
        issueId,
        notifTitle,
        notifMessage
      );
    }

    return updatedIssue;
  },

  /**
   * Fetch aggregate campus metrics
   */
  async getCampusStats() {
    if (!isSupabaseConfigured()) {
      return { total: 0, reported: 0, inProgress: 0, resolved: 0, urgent: 0 };
    }

    const { data, error } = await supabase
      .from('issues')
      .select('status, priority');

    if (error) {
      console.error('Error fetching stats:', error);
      return { total: 0, reported: 0, inProgress: 0, resolved: 0, urgent: 0 };
    }

    const issues = data || [];
    const total = issues.length;
    const reported = issues.filter(i => i.status === 'Reported').length;
    const inProgress = issues.filter(i => i.status === 'In Progress').length;
    const resolved = issues.filter(i => i.status === 'Resolved').length;
    const urgent = issues.filter(i => i.priority === 'Urgent' && i.status !== 'Resolved').length;

    return { total, reported, inProgress, resolved, urgent };
  },

  /**
   * Fetch analytics data for administration
   */
  async getAnalyticsData() {
    if (!isSupabaseConfigured()) {
      return null;
    }

    const { data, error } = await supabase
      .from('issues')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching analytics:', error);
      return null;
    }

    const issues = data || [];
    if (issues.length === 0) return null;

    const total = issues.length;
    const resolvedIssues = issues.filter(i => i.status === 'Resolved');
    const resolutionRate = Math.round((resolvedIssues.length / total) * 100);
    const urgentCount = issues.filter(i => i.priority === 'Urgent').length;

    // Average resolution time calculation
    let avgHours = 0;
    if (resolvedIssues.length > 0) {
      const totalTurnaroundMs = resolvedIssues.reduce((acc, curr) => {
        if (!curr.resolved_at) return acc;
        const created = new Date(curr.created_at).getTime();
        const resolved = new Date(curr.resolved_at).getTime();
        return acc + Math.max(0, resolved - created);
      }, 0);
      avgHours = Math.round((totalTurnaroundMs / (resolvedIssues.length * 3600000)) * 10) / 10;
    }

    // Category breakdown
    const categories = ['Water', 'Leakage', 'Tap', 'Sanitation', 'Drainage', 'Other'];
    const byCategory = categories.map(cat => ({
      category: cat,
      count: issues.filter(i => i.category === cat).length
    })).filter(c => c.count > 0);

    // Status breakdown
    const statuses = ['Reported', 'In Progress', 'Resolved'];
    const byStatus = statuses.map(st => ({
      status: st,
      count: issues.filter(i => i.status === st).length
    }));

    return {
      total,
      resolvedCount: resolvedIssues.length,
      resolutionRate,
      urgentCount,
      avgResolutionHours: avgHours,
      byCategory,
      byStatus
    };
  }
};

export default issueService;
